name: publish

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  release:
    types: [released]

jobs:
  publish:
    uses: TokTok/ci-tools/.github/workflows/haskell-publish.yml@master
    secrets:
      API_TOKEN_HACKAGE: ${{ secrets.API_TOKEN_HACKAGE }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  binaries:
    runs-on: ubuntu-22.04
    container: toxchat/toktok-stack:haskell
    steps:
      - uses: actions/checkout@v4
      - name: Build binaries
        run: stack build --copy-bins
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: /github/home/.local/bin
          if-no-files-found: error
